# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Set strict permissions on /etc/openstack-dashboard/local_settings"
  file:
    path: /etc/openstack-dashboard/local_settings
    mode: 0644
  tags:
    @ANSIBLE_TAGS@
