# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Set user/group ownership of /etc/openstack-dashboard/local_settings to root/horizon"
  file:
    path: /etc/openstack-dashboard/local_settings
    owner: "root"
    group: "horizon"
  tags:
    @ANSIBLE_TAGS@
