# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Set disable_password_reveal in /etc/openstack-dashboard/local_settings to 'True'"
  lineinfile:
    dest: /etc/openstack-dashboard/local_settings
    regexp: "^disable_password_reveal"
    line: "True"
  tags:
    @ANSIBLE_TAGS@
