# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Set password_autocomplete in /etc/openstack-dashboard/local_settings to 'False'"
  lineinfile:
    dest: /etc/openstack-dashboard/local_settings
    regexp: "^password_autocomplete"
    line: "False"
  tags:
    @ANSIBLE_TAGS@
