# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Set USE_SSL in /etc/openstack-dashboard/local_settings to 'True'"
  lineinfile:
    dest: /etc/openstack-dashboard/local_settings
    regexp: "^USE_SSL"
    line: "True"
  tags:
    @ANSIBLE_TAGS@
