documentation_complete: false
name: Physical and Environmental Protection
schema_version: 3.0.0
satisfies:

- control_key: PE-1
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-1 goes here.

        This answer can be multi-line.

- control_key: PE-2
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-2 goes here.

        This answer can be multi-line.

- control_key: PE-3
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-3 goes here.

        This answer can be multi-line.

- control_key: PE-4
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-4 goes here.

        This answer can be multi-line.

- control_key: PE-5
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-5 goes here.

        This answer can be multi-line.

- control_key: PE-6
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-6 goes here.

        This answer can be multi-line.

- control_key: PE-6 (1)
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-6 (1) goes here.

        This answer can be multi-line.

- control_key: PE-8
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-8 goes here.

        This answer can be multi-line.

- control_key: PE-9
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-9 goes here.

        This answer can be multi-line.

- control_key: PE-10
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-10 goes here.

        This answer can be multi-line.

- control_key: PE-11
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-11 goes here.

        This answer can be multi-line.

- control_key: PE-12
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-12 goes here.

        This answer can be multi-line.

- control_key: PE-13
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-13 goes here.

        This answer can be multi-line.

- control_key: PE-13 (2)
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-13 (2) goes here.

        This answer can be multi-line.

- control_key: PE-13 (3)
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-13 (3) goes here.

        This answer can be multi-line.

- control_key: PE-14
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-14 goes here.

        This answer can be multi-line.

- control_key: PE-14 (2)
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-14 (2) goes here.

        This answer can be multi-line.

- control_key: PE-15
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-15 goes here.

        This answer can be multi-line.

- control_key: PE-16
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-16 goes here.

        This answer can be multi-line.

- control_key: PE-17
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PE-17 goes here.

        This answer can be multi-line.
