documentation_complete: false
name: Personnel Security
schema_version: 3.0.0
satisfies:

- control_key: PS-1
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PS-1 goes here.

        This answer can be multi-line.

- control_key: PS-2
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PS-2 goes here.

        This answer can be multi-line.

- control_key: PS-3
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PS-3 goes here.

        This answer can be multi-line.

- control_key: PS-3 (3)
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PS-3 (3) goes here.

        This answer can be multi-line.

- control_key: PS-4
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PS-4 goes here.

        This answer can be multi-line.

- control_key: PS-5
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PS-5 goes here.

        This answer can be multi-line.

- control_key: PS-6
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PS-6 goes here.

        This answer can be multi-line.

- control_key: PS-7
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PS-7 goes here.

        This answer can be multi-line.

- control_key: PS-8
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        Narrative text on how product can be configured against PS-8 goes here.

        This answer can be multi-line.
