# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Set SESION_COOKIE_HTTPONLY in /etc/openstack-dashboard/local_settings to 'True'"
  lineinfile:
    dest: /etc/openstack-dashboard/local_settings
    regexp: "^SESSION_COOKIE_HTTPONLY"
    line: "True"
  tags:
    @ANSIBLE_TAGS@
