name: Validate content
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get compliance-masonry
        run: |
          go get -u -v github.com/opencontrol/compliance-masonry/cmd/masonry
      - name: Make
        run: |
          make clean all
      - name: Masonry Validate
        run: |
          ~/go/bin/masonry get
          ~/go/bin/masonry validate
